# Server settings
server:
  port: 8080
  servlet:

# Database settings
spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/${DB_NAME:voyagia}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver

    # Docker HikariCP settings
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # JPA settings
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Redis settings
  data:
    redis:
      host: "redis"
      port: 6379
      password: "${REDIS_PASSWORD:}"
      database: 0
      timeout: 60000ms
      connect-timeout: 10000ms
      jedis:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 2

# Logging settings
logging:
  level:
    root: INFO
    com.voyagia: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

  file:
    name:

# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    db:
      enabled: true

# JWT & Security Configuration
app:
  jwt:
    secret: "${JWT_SECRET}"
    expiration: ${JWT_EXPIRATION:86400}
    issuer: "${JWT_ISSUER:voyagia-backend-docker}"
    audience: "${JWT_AUDIENCE:voyagia-users}"

  # CORS config
  cors:
    allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,http://frontend:3000,http://frontend:5173}"
    allowed-methods: "${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}"
    allowed-headers: "${CORS_ALLOWED_HEADERS:*}"
    exposed-headers: "${CORS_EXPOSED_HEADERS:Authorization,Content-Type}"
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    max-age: ${CORS_MAX_AGE:3600}

# 📦 Custom Properties
voyagia:
  database:
    host: "postgres"
    port: 5432
    name: "${DB_NAME:voyagia}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    max-pool-size: 20
    min-pool-size: 5
    connection-timeout: 30000

  redis:
    host: "redis"
    port: 6379
    password: "${REDIS_PASSWORD:}"
    database: 0
    timeout: 60000
    max-active: 20
    max-wait: -1

# Docker environment information
info:
  environment: "docker"
  infrastructure:
    database: "PostgreSQL Container"
    cache: "Redis Container"
    network: "Docker Bridge Network"
